#pragma once

#define SPRITE_SPRITES 0
#define SPRITE_TURRET 0
#define SPRITE_ALPHABET 1
#define SPRITE_PLAYER_BULLET 2
#define SPRITE_PLAYER_BULLET_HOMMING 3
#define SPRITE_PLAYER_BULLET_FLAMETHROWER 4
#define SPRITE_PLAYER_BULLET_RAILGUN 5
#define SPRITE_SATELLITE 6
#define SPRITE_STREAM 7
#define SPRITE_RATTUNG 8
#define SPRITE_WEAPON_ICONS 9
#define SPRITE_POWERBLAST 11
#define SPRITE_ENERGYSHIELD 12
#define SPRITE_BASE 14
#define SPRITE_GAME_FG 15
#define SPRITE_WALL 16

#define SPRITE_BULLET_ENEMY_INDEX 20
#define SPRITE_EXPLOSION_INDEX 30
#define SPRITE_ENEMY_INDEX 40
#define SPRITE_LEVEL1_ENEMIES 41
#define SPRITE_LEVEL2_ENEMIES 42
#define SPRITE_SPACE_SERPENT 43

